### PR TITLE
Bugfix - cake 0.28.0 compatibility

### PR DESCRIPTION
**Pull request by JenasysDesign**
Address a Cake.build errors identified by myself and other file helper users.

### CODE REVIEW

**Comment by gep13** [comment]
@JenasysDesign this is covered in the release blog post for Cake 0.28.0:

https://cakebuild.net/blog/2018/05/cake-v0.28.0-released

i.e. the CakeTaskBuilder has changed in this new release.

**Comment by JenasysDesign** [comment]
Cheers @gep13 , I found the https://github.com/cake-contrib/Home/blob/master/Audit_for_Cake_0.26.0.md  along with https://github.com/cake-contrib/Home/blob/master/Audit_for_Cake_0.28.0.md

Those reports are the most useful as it helps me determine where I need to put effort into the community to fix the cake builds we have configured for clients.

**Comment by gep13** [comment]
@JenasysDesign I have reached out directly to the maintainer of MagicChunks, but as yet, I haven't heard anything back from him 😢

**Comment by JenasysDesign** [comment]
https://github.com/sergeyzwezdin/magic-chunks/issues/58, I've up voted that suggestion as well.

**Comment by JenasysDesign** [comment]
@gep13 have committed another PR to https://github.com/cake-contrib/Cake.Recipe/pull/224 cake.recipe to address the 0.28.0 API change you identified. Cheers. 
I've tested a manual changed to the Cake.FileHelpers\tools\Cake.Recipe.0.3.0-unstable0372\Content\tasks.cake file to confirm it would pass automated CI with that change.

**Comment by gitfool** [comment]
Updating to Cake 0.29.0 I'm now seeing the following during builds:
```
Installing addins...
The assembly 'Cake.FileHelpers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
```
It would be nice to get this merged soon. 😉

**Comment by skovsende** [comment]
I did a new PR(#25) and have pinged @Redth on the cake gitter chat.

**Comment by gep13** [comment]
@JenasysDesign thanks for doing this, but looks like this was covered in another PR.  I am going to go ahead and close this one out.

**Pull request closed without merging**
