### PR TITLE
Update to Cake.Core 0.26.1

### PR DESCRIPTION
**Pull request by Kemyke**

### CODE REVIEW

**Comment by Kemyke** [comment]
> C:\projects\cake-filehelpers\tools\OpenCover.4.6.519\SampleSln\Bom\Bom.csproj : error MSB4057: The target "pack" does not exist in the project.

The Cake.Recipe pack task try to pack all csproj files. `GetFiles(BuildParameters.SourceDirectoryPath + "/**/*.csproj") - GetFiles(BuildParameters.SourceDirectoryPath + "/**/*.Tests.csproj")` 

Is this a good practice? I think thats the cause of the failed appveyor build.

**Comment by gep13** [comment]
That Globbing pattern should be looking for project files directly in your Source/src folder.  Looks like you might have changed that value to point at the root folder, is that correct?

Cake.Recipe is very opinionated about certain things, the inclusion of a Source/src folder being one of them.

**Comment by Kemyke** [comment]
As you can see i only changed two files, the two `csproj` files. Nothing else.

**Comment by ghuntley** [comment]
This can be closed.

**Comment by gep13** [comment]
@Kemyke thanks again for this PR, however, this is not required as it has been superceded by another PR.

**Pull request closed without merging**
