### PR TITLE
Update project files to new format

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR updates the project files to the new csproj format. Functionally, everything remains the same in this PR, but it has two benefits:

1. The .NET CLI can be used to build/test the project/solution. This is a requirement to enable #10.
2. The project files are a lot cleaner, which makes editing them far easier.

The main disadvantage is that you can no longer build the project using Visual Studio 2015 or lower. The minimum compatible Visual Studio version is 2017 (latest), although you could also use Project Rider or VS Code, or even just use the command-line .NET CLI.

### CODE REVIEW

**Comment by gep13** [comment]
@ErikSchierboom nice!

For this to build correctly on AppVeyor, we will need to include this:

https://github.com/cake-contrib/Cake.HockeyApp/blob/develop/.appveyor.yml#L4

**Comment by ErikSchierboom** [comment]
@gep13 Ah yes, of course! I've updated the PR.

**Comment by ErikSchierboom** [comment]
@Redth Could you perhaps look at this PR? Once this is merged, I can then continue my work on .NET Core support.

**Comment by Redth** [comment]
@ErikSchierboom looks good, opens and works in VS for Mac still which is a must for me.

I think the next step is to turn Cake.FileHelpers into a shared project, then make `netstandard1.6` and `net45` library projects using the shared project to get your different compile targets.

**Comment by ErikSchierboom** [comment]
@Redth Thanks! I'll look into it.

**Comment by Redth** [comment]
So I started a branch: https://github.com/cake-contrib/Cake.FileHelpers/tree/netstandard 
This is more to experiment if we can just use netstandard1.6 and ditch net45 completely, but it looks like that may not be the case with 0.22... 

Might want to hold off on work for a bit.  This addin is very simple with no other dependencies so I'm using it to experiment with work being done on Cake to support netstandard.

**Comment by ErikSchierboom** [comment]
@Redth Yes, I was thinking along the same path. I'll hold off the work then. What error do you get with the netstandard version?

**Pull request merged**
